### ISSUE TITLE
FIx Sugarizer and Sugarizer Server compatibility errors

### ISSUE THREAD

**Issue by NikhilM98** [llaske/sugarizer-server#288] opened 2022-02-16 16:19 UTC
Sugarizer depends on Sugarizer Server as backend to support networking.

Sugarizer running on [try.sugarizer.org](https://try.sugarizer.org/index.html) seems to be running into multiple issues:
<img width="1792" alt="Screen Shot 2022-02-17 at 1 08 55" src="https://user-images.githubusercontent.com/24666770/154307276-015c0a5c-6ad8-4d90-99ee-d9ce6c43d3d4.png">

Tasks:
- Identify the source of different errors and create issues on the relevant repository
- Create a pull request on the relevant repository to fix the issue

Directions:
- The `dev` branch contains the latest code of Sugarizer and Sugarizer Server, so try to branch from `dev` branch.

**Comment by llaske** [comment] 2022-02-19 10:06
Hmmm. I can't reproduce it on my side.
Is it an issue related to an existing user? Do you have the same issue when creating a new user?

**Comment by NikhilM98** [comment] 2022-02-19 12:49
> Hmmm. I can't reproduce it on my side.

Yeah, I tried reproducing the error but I couldn't reproduce it either.

> Is it an issue related to an existing user? Do you have the same issue when creating a new user?

I created a new user while testing. 

<hr>

I was getting error 500 (Internal server error), so it was definitely not a network issue. It may be possible that server might have run into some temporary issue.

**Comment by NikhilM98** [comment] 2022-02-19 13:27
It seems that due to some reason, the user id was missing from the requests.

**Comment by llaske** [comment] 2022-02-26 20:49
I've explored the issue in past days to see if it could be related to session expiration but it's not.
I can't see a reason for the client to have a null user id except if you've deleted the browser cache.
So I'm closing the issue. We could reopen it if it happens again.

**Closed by llaske** 2022-02-26 20:49 UTC

**Comment by NikhilM98** [comment] 2022-02-26 23:18
I tested it again, this error occurs when I try to use try.sugarizer.org in incognito mode (I'm using Google Chrome on Mac.)

**Comment by llaske** [comment] 2022-02-28 08:36
@NikhilM98 I've tested with Google Chrome 98.0.4758.109 on Mac in Private Mode and it works so I can't reproduce this behavior. Did you change settings regarding cookies handling?
FYI there is limitation about using Sugarizer in Private Mode in Firefox (see [here](https://github.com/llaske/sugarizer/issues/361)) but there is no such limitation on Chrome.
